---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
kubernetesVersion: stable
controlPlaneEndpoint: "plane.rvloona.com:6443"
etcd:
  external:
    endpoints:
      - https://etcd.rvloona.com:2379
    caFile: /etc/kubernetes/pki/etcd/ca.crt
    certFile: /etc/kubernetes/pki/apiserver-etcd-client.crt
    keyFile: /etc/kubernetes/pki/apiserver-etcd-client.key
networking:
  serviceSubnet: "10.40.0.0/16"
  podSubnet: "10.30.0.0/16"
  dnsDomain: "cluster.local"